language: python

python:
  - '3.7-dev'  # Use dev case normal not found

install:
  - 'pip install pipenv'
  - 'pipenv install --dev'

script:
  - 'pipenv run invoke lint'
  - 'pipenv run pytest'

services:
  - docker
