version: '3'

services:
  app: &app
    build:
      context: .
      dockerfile: ./config/prod/app/Dockerfile
    image: aiohttp_prod_app
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  backend:
    <<: *app
    image: aiohttp_prod_backend
    restart: always
    ports:
      - 8080:8080
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./config/prod/postgres/Dockerfile
    image: aiohttp_prod_postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./volumes/backups:/backups
    env_file:
      - .env
    restart: always

  redis:
    image: redis
    volumes:
      - ./volumes/redis:/data/
    restart: always

  dbmate:
    image: amacneil/dbmate
    depends_on:
      - postgres
    volumes:
      - ./db:/db
    env_file:
      - .env
