version: '3'

services:
  app: &app
    build:
      context: .
      dockerfile: ./config/prod/app/Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env

  backend:
    <<: *app
    restart: always
    ports:
      - 8080:8080
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./config/prod/postgres/Dockerfile
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./volumes/backups:/backups
    env_file:
      - .env
    restart: always
