version: '3'

services:
  app: &app
    build:
      context: .
      dockerfile: ./config/dev/app/Dockerfile
    image: aiohttp_dev_app
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file:
      - .env

  backend:
    <<: *app
    image: aiohttp_dev_backend
    ports:
      - 8000:8000
    command: ./commands.py runserver

  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    env_file:
      - .env

  redis:
    image: redis
    ports:
      - 6379:6379
